### ISSUE TITLE
Source parameter in base path

### ISSUE THREAD

**Issue by Alexlbk35** [jncarter123/signalk-generic-pgn-parser#1]
Hello,
I'm trying to build a path that includes the pgn source parameter as in so:
electrical.ac.{src}.phase.A
I'm not a JS developer, but it looks like the base path is built out of available fields in the pgn and source is not part of the pgn I created and I have no idea how to include it in the base path. The pgn.h excerpt is below:

 {"AC Voltage / Frequency - Phase A",
     127747,
     PACKET_COMPLETE,
     PACKET_SINGLE,
     8,
     0,
     {{"SID", BYTES(1), 1, false, 0, ""},
      {"Connection Number", BYTES(1), 1, false, 0, ""},
      {"AC RMS Voltage Line to Neutral", BYTES(2), 0.1, false, "V", ""},
      {"AC RMS Voltage Line to Line", BYTES(2), 0.1, false, "V", ""},
      {"AC Frequency", BYTES(2), 0.1, false, "Hz", ""},
      {0}}}

**Comment by jncarter123** [comment]
I've not used that PGN, but it looks like "Connection Number" is what you would want to use to differentiate. You should be able to use electrical.ac.{Connection Number}.phase.A

**Comment by Alexlbk35** [comment]
I have already tried that, unfortunately my generator sets this value to 255 (i.e. undefined), the AC monitor sets it to 0, so the idea works, but the path is really ugly and doesn’t match the path for the PGNs that are parsed directly from can0.

What’s interesting is that the code does see an instance derived from src, but doesn’t use it.

Jun 15 23:38:40 2022-06-16T03:38:40.771Z signalk-generic-pgn-parser Looking for device instance of 4 
Jun 15 23:38:40 2022-06-16T03:38:40.773Z signalk-generic-pgn-parser Found deviceInstance 0

**Comment by jncarter123** [comment]
Try electrical.ac.{Instance}.phase.A

**Comment by Alexlbk35** [comment]
Tried that too – Instance always returns 0, so the values from different devices effectively get overwritten with every update.


electrical.ac.0.phase.B.acFrequency  511

	

electrical.ac.0.phase.B.acFrequency  60

**Comment by Alexlbk35** [comment]
I understand that this is not the way to do this, but I don’t feel comfortable requesting a pull since I never coded in JS and the last time I coded in anything Bush was in the office.

 

I modified the code as follows:

function getDeviceInstance(src) {

    app.debug('Looking for device instance of ' + src)

    const sources = app.getPath('/sources')

    let deviceInstance

    if (sources) {

      _.values(sources).forEach(v => {

        if (typeof v === 'object') {

          _.keys(v).forEach(id => {

            if (v[id] && v[id].n2k && v[id].n2k.src == src.toString()) {

              if (v[id].n2k.hasOwnProperty('deviceInstance')) {

        /*

                deviceInstance = v[id].n2k.deviceInstance

        */

                deviceInstance = v[id].n2k.src + '.' + v[id].n2k.deviceInstance

                app.debug('Found deviceInstance ' + deviceInstance)

              }

            }

          })

        }

      })

      return deviceInstance

    }

  }

 

n2kCallback = (msg) => {

      try {

        if (options.pgns && options.pgns.length > 0) {

          let fields = msg['fields']

 

          let details = options.pgns.find(({

            pgn

          }) => pgn === msg.pgn)

 

          if (details && (details.manufacturer == '' || details.manufacturer == fields['Manufacturer Code'])) {

 

            let instance = getInstance(fields, msg.src)

 

            if (!isNaN(parseInt(instance))) {

              let basePath = replace(details.basePath, fields, instance)

              app.debug('Basepath ' + basePath)

 

              let keys = []

              if (details.fields && details.fields.length > 0) {

                keys = details.fields.split(",").map(field => field.trim())

              } else {

                keys = Object.keys(fields)

              }

 

              handleDelta(fields, keys, basePath, msg.src, instance)

            } else {

              let basePath = replace(details.basePath, fields, instance)

              app.debug('Basepath ' + basePath)

                /*

              app.error('Instance not found for pgn ' + msg.pgn + ' source ' + msg.src)

                */

            }

          }

        }

 

It works as expected when the instance is defined, adds instance 0 when instance is not defined, so it could be improved, but it does do what I need at the moment.

 


electrical.ac.128.0.phase.A.acFrequency 

511.5

	06/16 01:34:04

signalk-generic-pgn-parser 


electrical.ac.128.0.phase.A.acRmsVoltageLineToLine 

6552.6

	06/16 01:34:04

signalk-generic-pgn-parser 


electrical.ac.128.0.phase.A.acRmsVoltageLineToNeutral 

6552.6

	06/16 01:34:04

signalk-generic-pgn-parser 


electrical.ac.128.0.phase.B.acFrequency 

511.5

	06/16 01:34:04

signalk-generic-pgn-parser 


electrical.ac.128.0.phase.B.acRmsVoltageLineToLine 

6552.6

	06/16 01:34:04

signalk-generic-pgn-parser 


electrical.ac.128.0.phase.B.acRmsVoltageLineToNeutral 

6552.6

	06/16 01:34:04

signalk-generic-pgn-parser 


electrical.ac.128.undefined.phase.A.current 

6552.6

A

06/16 05:34:04

canbus.128 (127744)


electrical.ac.128.undefined.phase.A.power 

0

	06/16 05:34:04

canbus.128 (127744)


electrical.ac.128.undefined.phase.B.current 

6552.6

A

06/16 05:34:04

canbus.128 (127745)


electrical.ac.128.undefined.phase.B.power 

0

	06/16 05:34:04

canbus.128 (127745)


electrical.ac.128.undefined.phase.C.current 

6552.6

A

06/16 05:34:05

canbus.128 (127746)


electrical.ac.128.undefined.phase.C.power 

0

	06/16 05:34:05

canbus.128 (127746)


electrical.ac.4.0.phase.A.acFrequency 

60

	06/16 01:34:07

signalk-generic-pgn-parser 


electrical.ac.4.0.phase.A.acRmsVoltageLineToLine 

238.2

	06/16 01:34:07

signalk-generic-pgn-parser 


electrical.ac.4.0.phase.A.acRmsVoltageLineToNeutral 

119.1

	06/16 01:34:07

signalk-generic-pgn-parser 


electrical.ac.4.0.phase.A.current 

2.3

A

06/16 05:34:07

canbus.4 (127744)


electrical.ac.4.0.phase.A.power 

238

	06/16 05:34:07

canbus.4 (127744)


electrical.ac.4.0.phase.B.acFrequency 

60

	06/16 01:34:04

signalk-generic-pgn-parser 


electrical.ac.4.0.phase.B.acRmsVoltageLineToLine 

237.8

	06/16 01:34:04

signalk-generic-pgn-parser 


electrical.ac.4.0.phase.B.acRmsVoltageLineToNeutral 

118.9

	06/16 01:34:04

signalk-generic-pgn-parser 


electrical.ac.4.0.phase.B.current 

0

A

06/16 05:34:04

canbus.4 (127745)


electrical.ac.4.0.phase.B.power 

0

	06/16 05:34:04

canbus.4 (127745)

 

As you can see undefined value for source 128 turns into 0 with the parser. The values for 128 is garbage since the generator is off.

Shore power is on however and the values from canbus both make sense and are consistent.

Feel free to improve on my attempt as you see fit.

 

--Alex

**Comment by jncarter123** [comment]
The problem with source is that it can change. You might add a new device or reset the NMEA network and all or some of the devices will get new source id. If all of your devices return instance 0, the proper thing would be to program other instance numbers, ie 0= shore, 1= generator, etc. 

I will go ahead and add source as an option. I'll also look into the ability to use CANNAME which is a hardcoded address of the device, similar to a MAC address on a computer.

**Comment by Alexlbk35** [comment]
I am looking into an ability to set instance ID on the generator NMEA interface. It’s proprietary engine interface, so it’s not trivial. I understand that source will change, however it will change across the board for all the pgns, so the data output will be consistent. 

Thank you for your help.

**Comment by jncarter123** [comment]
Ok sounds good. The problem with source being part of the signalk path is that if it changes, then that will cause issues with other integrations like WilhelmSK and InfluxDB. I should be able to get source added as an option this evening.

**Comment by Alexlbk35** [comment]
Got a positive yet cryptic response from generator manufacturer.

you can change the NMEA device instance (ISO-ECU instance). Use the PGN 126208 to request the ISO address claim message PGN 60928. Specify the fields 3 and 4 in the request.

I have no clue which utility to use to accomplish this, but looks like it’s doable.

**Comment by jncarter123** [comment]
I'm not sure what devices you have available to you. I know Maretron makes this very easy with the USB100 and N2KAnalyzer software. Otherwise take a look at https://www.nmea.org/Assets/20140109%20nmea-2000-corrigendum-tc201401031%20pgn%20126208.pdf page 14. It says "This Group Function is especially useful when configuring an instance or reference to be used by a node when transmitting a PGN such as PGN 127508. Use Fields 7, 9 and 10 to identify the currently assigned instance value. Use Fields 8, 13 and 14 to identify the new assigned instance value." It's been awhile since i deep dove into this. The guys on the SignalK slack might be able to give some help to setting the instance as well.

**Comment by jncarter123** [comment]
I just published v1.4. It should be available in the app store shortly. You can use {Source} or {canName} in the path template.

**Comment by Alexlbk35** [comment]
Much appreciated.
